variables:
    GIT_SUBMODULE_STRATEGY: recursive

compile_pdf:
    image: texlive/texlive
    before_script:
        - apt install qpdf -y
    script:
        - latexmk -lualatex beamer.tex
        - qpdf --linearize paper.pdf beamer.pdf
    after_script:
    artifacts:
        paths:
        - beamer.pdf